export const data = {
  products: [
    {
      id: 1,
      name: "Product 1",
      image: "https://via.placeholder.com/150",
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "Some description about product 1",
    },
    {
      id: 2,
      name: "Product 2",
      image: "https://via.placeholder.com/150",
      price: 10,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "Some description about product 1",
    },
    {
      id: 3,
      name: "Product 3",
      image: "https://via.placeholder.com/150",
      price: 90,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "Some description about product 1",
    },
    {
      id: 4,
      name: "Product 4",
      image: "https://via.placeholder.com/150",
      price: 29,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "Some description about product 1",
    },
  ],
};
